spring:
  application:
    name: udemy-curso-erudio

  datasource:
    url: jdbc:postgresql://localhost:5432/curso_erudio_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
