CREATE TABLE public.person (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                               first_name VARCHAR(50)  NOT NULL,
                               last_name  VARCHAR(80)  NOT NULL,
                               gender     VARCHAR(6)   NOT NULL,
                               address    VARCHAR(90)  NOT NULL,
                               birth_day  TIMESTAMP(6) WITHOUT TIME ZONE,
                               CONSTRAINT person_pkey PRIMARY KEY (id)
);